# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4654ddb1a4a52f6c7307df8116d5728ef53c8cce35a8205553d6b3ecd544dadae1b3c9dd75196c8d25f505b3acf57e8db68f19d596fa3d419822f24e3ee08de5

test:
  secret_key_base: b93e78e1cc60f6fd8d627d546d2d86d49d529e2a8840583f61d2463343fdcef97305452d04e1008441633b052edd6cb2a63a4c9a223f67be7b37edfbaad13d26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
